name = "rf-solutions"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./client/build"

[[d1_databases]]
binding = "DB"
database_name = "rf-solutions-db"
database_id = "401fd303-c846-4df9-9daa-3c8e1fb93c0a"
